

services:
  postgres:
    image: postgres:15
    container_name: olist_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - olist_network

  airflow:
    image: apache/airflow:2.8.1
    container_name: olist_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - postgres
    networks:
      - olist_network
    command: standalone

  streamlit:
    image: python:3.11-slim
    container_name: olist_streamlit
    working_dir: /app
    volumes:
      - ./dashboard:/app
    ports:
      - "8501:8501"
    networks:
      - olist_network
    command: sh -c "pip install streamlit psycopg2-binary pandas plotly --quiet && streamlit run app.py"
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  olist_network:
    driver: bridge